 module.exports = Object.freeze({
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  TRANSFERRED: "TRANSFERRED",
  ESCALATED: "ESCALATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  EVIDENCE_ADDED: "EVIDENCE_ADDED",
  COMMENT_ADDED: "COMMENT_ADDED",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED",
  DELETED: "DELETED",
  RESTORED: "RESTORED",
});